export const DRAUGHT_API_REQUEST = 'DRAUGHT_API_REQUEST';
export const DRAUGHT_API_PLACE_SUCCESS = 'DRAUGHT_API_PLACE_SUCCESS';
export const DRAUGHT_API_DRINK_SUCCESS = 'DRAUGHT_API_DRINK_SUCCESS';
export const DRAUGHT_API_ERROR = 'DRAUGHT_API_ERROR';
export const DRAUGHT_INITIAL_LOAD_SUCCESS = 'DRAUGHT_INITIAL_LOAD_SUCCESS';