export const DRINK_RATING_API_REQUEST = "DRINK_RATING_API_REQUEST";
export const DRINK_RATING_INITIAL_LOAD_SUCCESS = "DRINK_RATING_INITIAL_LOAD_SUCCESS";
export const DRINK_RATING_API_SUCCESS = 'DRINK_RATING_API_SUCCESS';
export const DRINK_RATING_API_ERROR = 'DRINK_RATING_API_ERROR';