export const DRINK_API_REQUEST = 'DRINK_API_REQUEST';
export const DRINK_API_SUCCESS = 'DRINK_API_SUCCESS';
export const DRINK_API_ERROR = 'DRINK_API_ERROR';
export const DRINK_API_INITAL_LOAD_SUCCESS = 'DRINK_API_INITAL_LOAD_SUCCESS';