export const OWNERSHIP_API_REQUEST = "OWNERSHIP_API_REQUEST";
export const OWNERSHIP_INITIAL_LOAD_SUCCESS = "OWNERSHIP_INITIAL_LOAD_SUCCESS";
export const OWNERSHIP_API_SUCCESS = 'OWNERSHIP_API_SUCCESS';
export const OWNERSHIP_API_ERROR = 'OWNERSHIP_API_ERROR';