export const PLACE_RATING_API_REQUEST = "PLACE_RATING_API_REQUEST";
export const PLACE_RATING_INITIAL_LOAD_SUCCESS = "PLACE_RATING_INITIAL_LOAD_SUCCESS";
export const PLACE_RATING_API_SUCCESS = 'PLACE_RATING_API_SUCCESS';
export const PLACE_RATING_ERROR = 'PLACE_RATING_ERROR';