export const PLACE_API_REQUEST = 'PLACE_API_REQUEST';
export const PLACE_API_SUCCESS = 'PLACE_API_SUCCESS';
export const PLACE_API_ERROR = 'PLACE_API_ERROR';
export const PLACE_API_INITIAL_LOAD_SUCCESS = 'PLACE_API_INITIAL_LOAD_SUCCESS';