export const SESSION_API_REQUEST = 'SESSION_API_REQUEST';
export const SESSION_API_AUTH_SUCCESS = 'SESSION_API_AUTH_SUCCESS';
export const SESSION_API_ERROR = 'SESSION_API_ERROR';
export const SESSION_LOG_OUT = 'SESSION_LOG_OUT';
