export const USER_API_REQUEST = "USER_API_REQUEST";
export const USER_INITIAL_LOAD_SUCCESS = "USER_API_INITIAL_LOAD_SUCCESS";
export const USER_API_SUCCESS = 'USER_API_SUCCESS';
export const USER_API_ERROR = 'USER_API_ERROR';